version: '3'
services: 
    laravel:
        environment:
            - DB_HOST=mariadb
            - DB_USERNAME=my_user
            - DB_DATABASE=my_database
            - DB_PASSWORD=my_password
        depends_on:
            - mariadb
        volumes: 
            - laravel:/app/public/uploads
        build: .

    mariadb:
        image: 'docker.io/bitnami/mariadb:10.2-debian-10'
        volumes: 
            - database:/bitnami/mariadb/data
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=my_user
            - MARIADB_DATABASE=my_database
            - MARIADB_PASSWORD=my_password
    nginx:
        image: nginx
        volumes: 
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data:/app
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443
volumes: 
    certs:
    laravel:
    database:
